kind: Pod
apiVersion: v1
metadata:
  name: net-demo
spec:
  containers:
    - name: busy1
      image: busybox
      command:
      - sleep
      - "3600"
    - name: busy2
      image: busybox
      command:
      - sleep
      - "3600"
