kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
    - name: secretbox
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: mysecret
          mountPath: /secretstuff
  volumes:
    - name: mysecret
      secret:
        secretName: mysecret
