apiVersion: v1
kind: Pod
metadata:
  name: shared-volume
spec:
  containers:
  - image: centos:7
    name: pod1
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /centos1
        name: myvolume
  - name: pod2
    image: centos:7
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /centos2
        name: myvolume
  volumes:
    - name: myvolume
      emptyDir: {}

