kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: nwp-namespace
  name: deny-to-other-namespaces
spec:
  podSelector:
    matchLabels:
  policyTypes:
    - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: nwp-namespace              
