apiVersion: v1
kind: Pod
metadata:
  name: question-8
spec:
  containers:
  - image: alpine
    name: alpine
    command:
    - sleep
    - "3600"
    env:
    - name: myuser
      valueFrom:
        configMapKeyRef:
          name: mycm
          key: myuser
