apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: question-9
spec:
  selector:
    matchLabels:
      name: nginx-ds
  template:
    metadata:
      labels:
        name: nginx-ds
    spec:
      containers:
      - name: nginx
        image: nginx
