apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: question-6
  name: question-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: question-6
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
status: {}
