---
apiVersion: v1
kind: Pod
metadata:
  name: busy-secure
  namespace: secure
  labels:
    app: busy-secure
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - "3600"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nwp
  labels:
    app: nginx-nwp
spec:
  containers:
  - image: nginx
    name: nginx
---
---
apiVersion: v1
kind: Pod
metadata:
  name: busy-secure-rouge
  namespace: secure
  labels:
    app: not-allowed
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - "3600"
---
