apiVersion: v1
kind: Pod
metadata:
  name: question-3
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 10000']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "for i in {1..1}; do touch /data/runfile.txt; sleep 1; done"]
