apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testsvc
  name: myservice
spec:
  ports:
  - port: 9376
    protocol: TCP
    targetPort: 80
  selector:
    app: testsvc
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testsvc
  name: mydb
spec:
  ports:
  - port: 9377
    protocol: TCP
    targetPort: 80
  selector:
    app: testsvc
status:
  loadBalancer: {}
