apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testsvc
  name: testsvc
  namespace: net-demo1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: testsvc
status:
  loadBalancer: {}
